FROM gitlab/gitlab-ee:latest
RUN apt-get update --fix-missing
#RUN apt-get install -y python3-pip python-dev-is-python3 build-essential libpq-dev nginx  python3-certbot-nginx 
#RUN apt-get install -y nginx nginx-common 
#RUN apt-get install -y  nginx-common
#RUN apt-get install -y python3-pip python-dev-is-python3 build-essential libpq-dev python3-certbot-nginx
#RUN apt-get update --fix-missing  
#RUN apt-get install -y python3-certbot-nginx

#RUN apk add certbot certbot-nginx 
#COPY . /app
#COPY ./nkosl_blog.conf /etc/nginx/sites-enabled/default
#WORKDIR /gitlab

#RUN pip install -r requirements.txt

#RUN mkdir -p /etc/letsencrypt/live/mario-nkosl-app.duckdns.org/

#COPY /etc/letsencrypt/live/mario-nkosl-app.duckdns.org/fullchain.pem  /etc/letsencrypt/live/mario-nkosl-app.duckdns.org/fullchain.pem
#COPY /etc/letsencrypt/live/mario-nkosl-app.duckdns.org/privkey.pem  /etc/letsencrypt/live/mario-nkosl-app.duckdns.org/privkey.pem  
#COPY ./default.conf /etc/nginx/conf.d/default.conf

#RUN pip install -r requirements.txt

#ENTRYPOINT ./docker_entrypoint.sh

#RUN nginx
#RUN certbot -m --nginx -d mario-nkosl-app.duckdns.org
#RUN certbot certonly --nginx --agree-tos -m mario.jalsovec@fer.hr -d mario-nkosl-gitlab2.duckdns.org
#COPY ./nkosl_blog.conf /etc/nginx/conf.d/default.conf

#COPY ./mario-nkosl-gitlab2.duckdns.org/ /etc/letsencrypt/live/mario-nkosl-gitlab2.duckdns.org/

#COPY ./default.conf /etc/nginx/sites-enabled/default
#COPY ./default.conf /etc/nginx/conf.d/default.conf
#COPY ./fullchain.pem /etc/letsencrypt/live/mario-nkosl-gitlab2.duckdns.org/fullchain.pem
#COPY ./privkey.pem /etc/letsencrypt/live/mario-nkosl-gitlab2.duckdns.org/privkey.pem

#RUN nginx
#RUN certbot certonly --nginx --agree-tos -m mario.jalsovec@fer.hr -d mario-nkosl-gitlab2.duckdns.org
